name: Deploy to Nest

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into Hack Club Nest and restart container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.NEST_HOST }}
          username: ${{ secrets.NEST_USER }}
          key: ${{ secrets.NEST_SSH_KEY }}
          script: |
            git pull origin main
            
            # Check if BOT_TOKEN is set
            if [ -z "${{ secrets.BOT_TOKEN }}" ]; then
              echo "Error: BOT_TOKEN is not set!"
              exit 1
            fi

            docker stop atlas_container || true
            docker rm atlas_container || true
            docker build -t atlas .

            docker run -d --name atlas_container \
              -e prod=${{ secrets.BOT_TOKEN }} \
              -e ENV=prod \
              -e MONGO=${{ secrets.DATABASE_AUTH }} \
              atlas