name: Deploy to Nest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into Hack Club Nest and restart container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.NEST_HOST }}
          username: ${{ secrets.NEST_USER }}
          key: ${{ secrets.NEST_SSH_KEY }}
          script: |
            # Start the container if it's not running
            if [ "$(docker ps -q -f name=atlas_container)" = "" ]; then
              docker start atlas_container || true
            fi

            # Run git commands inside the container
            docker exec atlas_container bash -c "
              cd /app || exit 1  # Ensure we're in the right directory inside the containerz1
              git reset --hard  # Reset any changes
              git pull origin main --force  # Pull latest changes
            "

            # Restart the container to apply changes
            docker stop atlas_container || true
            docker rm atlas_container || true
            docker build --no-cache -t atlas .

            docker run -d --name atlas_container \
              -e prod=${{ secrets.BOT_TOKEN }} \
              -e ENV=prod \
              -e MONGO=${{ secrets.DATABASE_AUTH }} \
              atlas
